### ISSUE TITLE
Host parameter is ignored

### ISSUE THREAD

**Issue by vasuems** [node-saml/passport-saml#169]
I have configured host, callbackUrl parameters along with path. Path value is considered. host and callbackUrl values are ignored. Instead of the configured host value, ip is used to generate AssertionConsumerServiceUrl. For example, my AssertionConsumerServiceUrl should be https://domainnmae/login/callback. Instead the AssertionConsumerServiceUrl is http:ip/login/callback. Because of this, post the authentication, the request fail to reach the call back function.

**Comment by pdspicer** [comment]
host option is used for metadata generation. when generating authnRequests, the value from req.headers.host is used (protocol comes from req.protocol as well if options.protocol is not set). Are you potentially using a reverse proxy that might be terminating SSL and/or not setting the host header properly?

**Comment by nudoru** [comment]
I'm having the same issue. My app is configured as shown below but the AssertionConsumerServiceUrl always goes back to http and my app fails the redirect.

path: '/login/callback', 
callbackUrl: 'https://domain.com/login/callback',
entryPoint: 'https://domain.com/idp/',
protocol: 'https',

**Comment by mx781** [comment]
Indeed it seems that passing callbackUrl in options gets ignored for some reason. We resolved the issue by passing `protocol='https://'` instead of just "https".

**Comment by theaccordance** [comment]
Is there a justification for using `req.headers.host` over the defined value for `this.options.host`?  

This is causing problems on my end, as my clients are making a call to our backend (app.server.com) to start the SAML request via an alias (app1.server.com).  Since the header contains the alias, that is in turn being passed to third-party SAML providers, which aren't aware of our aliases & don't have them included on their whitelists.  

IMO if we're setting a host value, that should be the value used by the host before it uses an implied value.

**Comment by ahavriluk** [comment]
I agree! There is no reason to pull the host from req.headers.host if this.options.host is provided.

**Comment by cjbarth** [comment]
I believe there may be more at play here than it first appears. I would expect in the case of @theaccordance use-case, that you'd have another federation or a redirection in order to handle the different domains. It seems that it would actually be undesirable to be able to configure things in such a way as to allow piggy-backing on another federation; it might even be considered a security issue (though I do acknowledge that using a `host` header does have its own implications for security).

As @pdspicer mentioned, `options.host` is for metadata generation. It follows that the metadata that is generated should match the requests that your server should be handling, so really `options.host` and `req.headers.host` should match. In cases where they don't, I would expect that condition to be exceptional and for the authentication to fail.

**Comment by markstos** [comment]
@cjbarth I'm OK with adding a check to see if `options.host` matches `req.headers.host`, or drop considering `req.headers.host` completely-- the less user input we trust, the better.

**Comment by giacomobartoli** [comment]
@mx781 I am experiencing the same issue. How did you solve it?
Currently my configuration is:

```
path: '/login/callback',
host: 'mywebserver.mybluemix.net',
protocol: 'https://',
callbackUrl: 'https://mywebserver.mybluemix.net/login/callback'
```

However, the request always goes to 
`AssertionConsumerServiceURL="http://mywebserver-dev.eu-de.mybluemix.net/login/callback"`

According to the doc, If I explicit the callbackUrl then it should be used that one in request. If not specified, it is created by concatenating **protocol** + **host** + **path**. Neither works right now.

**Comment by markstos** [comment]
@giacomobartoli You could try patching the code as described in my comment above.

**Comment by giacomobartoli** [comment]
@markstos that worked, but I still run into error 400 bad request. Is there a specific reference for Shibboleth v3 requests?

**Comment by markstos** [comment]
Hmm, no, but a number of my customers are using Shibboleth IdPs with our passport-saml SdP without a problem.

Use a SAML tracer to dig into the details of the 400 error.


https://chrome.google.com/webstore/detail/saml-tracer/mpdajninpobndbfcldcmbpnnbhibjmch?hl=en

**Comment by cjbarth** [comment]
@markstos et. al, as near as I can tell, the current codebase still has this problem. From the link above, [here](https://github.com/node-saml/passport-saml/blob/4d97ffcb7918526cfc6101207fe04d14a0abd23e/lib/passport-saml/saml.js#L81-L94) is the code under discussion, and [here](https://github.com/node-saml/node-saml/blob/cdabb85cbe5b44a799dae266bd918376ccbdb65b/src/saml.ts#L194-L211) is the current code.

Does something need to be done with this, or should we close this item?

P.S. I'd love to close off all the open items in `passport-saml` that are now actually `node-saml` items. Either we decide to do them and move the item over (or just do the work), or we close the item since it no longer applies to `passport-saml`.

**Comment by cjbarth** [comment]
Closed by https://github.com/node-saml/node-saml/pull/224
