### ISSUE TITLE
IdP-initiated SLO

### ISSUE THREAD

**Issue by arneroen** [node-saml/passport-saml#221]
I'm struggling to make IdP-initiated SLO work. As per several examples, I have the following routes:
```
app.post('/logout/callback', function(req, res) {
        req.logout();
        res.redirect('/');
});
app.get("/logout", function(req, res) {
        if (!req.user) res.redirect("/");
        console.log("initiating logout", req.log, req.user);
        return passport._strategy("saml").logout(req, function(err, uri) {
            return res.redirect(uri);
        });
});
```

In addition, logoutCallbackUrl is defined as '/logout/callback'. This works fine for SP-initiated logout. Obvivously not for IdP-initiated SLO, though, as being contacted at /logout/callback will not prompt the server to reply with a logoutResponse. I've not found any examples for how to implement IdP-initiated SLO. 

I've found [methods in the code](https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/saml.js#L251), that are generating the logoutResponse, which leads me to believe that IdP-initiated SLO is probably implemented.  However, the beginning of the "chain of calls" to get to it is the "authenticate" functionality. 

I'd greatly appreciate any help with getting this to work! Thanks!

**Comment by jonathanpdiaz** [comment]
hey @arneroen.
Have you found something else on this? I entered into the issues section to write exactly what you describe.
I'm getting the `LogoutRequest` from my Identity Provider (One Login), but the API of the strategy doesn't seem to handle it.
Any comment would be much appreciated.
Thanks!

**Comment by Brynjulf** [comment]
@arneroen, @jonathanpdiaz  you should change your callback from a post to a get. That fixed the issue for me.

**Comment by jonathanpdiaz** [comment]
I forgot to answer my own question after I found the issue. The library works perfectly.
In my case, we implemented the Single Logout using HTTP Redirect. 
What would this mean? It means that after I hit log out on any Service Provider [SP] (my app is one of them) passport-saml will generate a SAML Request XML that will log out this particular SP on the IdP and **the browser** will be redirected to the next SP that shares a session that needs to log out. To do this, the IdP will go to that particular SP and use the SLO endpoint.

One extra thing to consider is that the Identity Provider [IdP] will also hit the SLO endpoint to confirm the logout at the end. There, you can redirect your site to the login page.

Looks like this: (remember that is **the browser** who will be redirected to each site -one by one- that means that you have the information of the current session that is logged in each cookie that enables you to logout.)

![sp-slo](https://user-images.githubusercontent.com/2194027/31974490-759eb398-b902-11e7-81fd-5e8c1b827fd1.jpg)

Long story short, here is my current implementations that seem to work so far.
```
/**
 * Logout from SP to IdP.
 * We need a logged in user to log out.
 */
router.get('/logout', isAuthenticated(), samlLogout);

/**
 * IdP notifies logout.
 * Possible cases:
 * 1: same SP requested logout, IdP confirms logout.
 * 2: IdP request logout after receive logout request from SP that shared a session.
 * note: we can't use isAuth here, we need to redirect the browser.
 */
router.get(
  '/slo',
  (req, res, next) => {
    if(req.session.passport && req.session.passport.user) {
      req.user = req.session.passport.user;
      return next();
    } else {
      return res.redirect('/auth/saml');
    }
  },
  samlLogout
);

/**
 * Generate a Logout Request.
 * Redirect to this request URL.
 * note: SAML auth internally requires a req.user object with this 2 properties:
 *  '@Format': req.user.nameIDFormat,
 *  '#text': req.user.nameID
 */
function samlLogout(req, res) {
  try {
    const strategy = passport._strategy('saml');
    strategy.logout(req, function(error, requestUrl) {
      if(error) console.log(`Can't generate log out url: ${err}`);
      req.logOut();
      // passport-saml is not removing the session.
      delete req.session.passport;
      res.redirect(requestUrl);
    });
  } catch(err) {
    if(err) console.log(`Exception on URL: ${err}`);
    req.logOut();
    delete req.session.passport;
    res.redirect('/auth/saml');
  }
}
```

We use this API on a Single Page App. In our context, if we have the passport user, we are good to go.
So the isAuthenticated method only needs to check this.

```
import compose from 'composable-middleware';

/**
 * Attaches the user object to the request if authenticated
 * Otherwise returns 403
 */
export function isAuthenticated() {
  return compose().use(function(req, res, next) {
    if(req.session.passport && req.session.passport.user) {
      // after auth, we get a passport object.
      req.user = req.session.passport.user;
      return next();
    } else {
      return res.status(403).send({
        message: 'Session expired.',
      });
    }
  });
}
```

Hope it helps to someone else, it took me a little bit to figure it out.

**Comment by chveragad** [comment]
We too have a situation where login is IDP-initiated.  Our current application utilizes redis to hold the user session.  I have several questions and hopeful for an answer:
1) From the sample I got [https://github.com/gbraad/passport-saml-example](url), it is used with main node module passport.  Is the main passport node module required to use for passport-saml? How would it work with redis then?
2) Can passport-saml be used to validate, decrypt and digest the SAMLResponse from an IDP initiated callback?

**Comment by cjbarth** [comment]
@sagarwalsf @chveragad , yes IdP initiated sign on should work just fine if your callback URLs are set up correctly; I've gotten it to work.

**Comment by umardraz** [comment]
@jonathanpdiaz

I tried your solution here is my code

```
router.get('/logout', isAuthenticated(), samlLogout);

router.get(
    '/slo',
    (req, res, next) => {
      if(req.session.passport && req.session.passport.user) {
        req.user = req.session.passport.user;
        return next();
      } else {
        return res.redirect('/auth/saml/login');
      }
    },
    samlLogout
);

function samlLogout(req, res) {
    try {
      const strategy = passport._strategy('saml');
      strategy.logout(req, function(error, requestUrl) {
        if(error) console.log(`Can't generate log out url: ${err}`);
        req.logOut();
        delete req.session.passport;
        res.redirect(requestUrl);
      });
    } catch(err) {
      if(err) console.log(`Exception on URL: ${err}`);
      req.logOut();
      delete req.session.passport;
      res.redirect('/auth/saml/login');
    }
  }

```
Now the problem is whenever I tried to logout from my Wordpres sites then on successful logout they always get **nodejs site /auth/saml/login page** rather then their own wordpress login page.

Would you please help me how I can fix this

**Comment by abcd-ca** [comment]
> @arneroen, @jonathanpdiaz you should change your callback from a post to a get. That fixed the issue for me.

Hey, what would that look like? Do you mean to change this line? `res.redirect(requestUrl);`

**Comment by Brynjulf** [comment]
@abcd-ca 
```
app.post('/logout/callback', function(req, res) {
        req.logout();
        res.redirect('/');
});
```
should be changed to 
```
app.get('/logout/callback', function(req, res) {
        req.logout();
        res.redirect('/');
});
```
Not sure if this is still valid as i haven't been using this package for years

**Comment by abcd-ca** [comment]
@Brynjulf thank you for your reply. I think you probably meant that in the reverse order, changing from `get` to `post` but I appreciate you clarifying which part you'd change. 
 
For the benefit of anyone else trying to figure this out, `res.redirect` will create a `GET` request with a 302 (redirect) HTTP status code regardless of what method (get/post) the SP uses. 
 
If you call `res.redirect(307, requestUrl)` then the 307 indicates to the browser to preserve the method from the parent route. if you use `app.post...` then `res.redirect(307, requestUrl)` will make a POST request to the IdP. 

Note, `requestUrl` comes from `strategy.logout(req, function(error, requestUrl)...`

Regardless, with IdP using SAML 2.0 on ADFS, this does not work for me yet. Perhaps I need to add a signature to my logout request (though I am successfully doing SSO without signing – it's only SLO that is failing)

**Comment by srd90** [comment]
@abcd-ca @Brynjulf SAML SLO involves passing `LogoutRequest` and `LogoutResponse` messages back and forth.

Look at the picture at comment https://github.com/node-saml/passport-saml/issues/221#issuecomment-339179355

If your application is `SP1` at that picture following things happen from you applications point of view (in following order):
* user has clicked logout (single logout button)
* your application must terminate local session
* your application sends `LogoutRequest` to IdP via POST or redirect binding (which ever is better for you and which ever IdP support)
* [ *IdP propagates SLO to all services which participates to SSO session. Your application - SP1 - is not involved at this stage. When IdP has propagated `LogoutRequest` to all involved services and when it has received `LogoutResponse` response messages from all those application it shall report result of SLO to your application* ]
* your application's SLO callback receives `LogoutResponse` message from IdP via binding you have communicated to IdP (via metadata or by manually provisioning to IdP).  `LogoutResponse` contains result of triggered SLO operation (whether it was successfull or whether partial logout from some services etc.)

If your application is e.g. `SP2` at that picutre following things happens (and are expected from your application) and this scenario is **IdP-initiated SLO from your SP/application point of view**:
* [ *user has initiated SLO at some service* ]
* IdP propagates `LogoutRequest` to your application's logout callback via redirect or post binding (depending what you have configured to IdP via SP metadata or manually)
* your application must terminate user's session
* your application must send `LogoutResponse` message as a response to IdP. `LogoutResponse` must not say operation was success if your application was not able to terminate session designated by  information at `LogoutRequest` sent to your application by IdP.

This issue ( #221 ) has multiple examples related to SLO. None of the examples contain proper SLO. None of those examples care to send `LogoutResponse` in case of IdP initiated-SLO. All of the examples incorrectly redirect to e.g. application main page. User's browser is at this point busy propagating SLO e.g. by running logout requests at iframes at IdP - navigation bar contains IdP's address - or if IdP uses especially error prone approach it has initiated redirect from SP to SP and if one SP is behaving badly logout propagation stops there. Examples in this issue contains badly behaving SPs. Furthermore there are few issues here and at stackoverflow where questions are something like  "why does SLO work when it is initiated from my service but does not work if my service is second SP" or "why does SLO stops at service X's main/login page" and if those questions contain some code snippets usually it is quite obvious that `LogoutResponse`s are not being sent by applications (for `LogoutRequest`s sent by IdP) and SLO propagation fails.

`passport-saml` has broken support for IdP initiated logout (i.e. incoming `LogoutRequest` handling). You must delegate that request from your logout callback  - counter intuitively - to passport-saml's `authenticate` method and at the end of the day processing ends up here (link poins to `3.2.1`):
https://github.com/node-saml/passport-saml/blob/6ba76ba3a015fea96a2dd38f661a6c1f85bc44a1/src/passport-saml/strategy.ts#L61-L73 (reverse engineer from that code block and you'll see how it ends there).

Aforementioned code block does not work correctly with modern browsers. It fails to terminate session most of the time and it fails to report proper status at `LogoutResponse` (it has hardcoded success  status).

For more information about problems of `passport-saml`'s SLO see issue #419 ( some of the links at that issue point to `bergie/passport-saml`. For the record that issue was created before `passport-saml` repository, issues and development was moved over from `bergie/passport-saml` to `node-saml/passport-saml`).

btw. use e.g. some saml tracer browser plugin and sign in to few services which use SSO and SLO and share same IdP and which work correctly and observe SAML Logout request/response exchanged during SLO.

**Comment by johndegey** [comment]
Hi all,

I started a new Vue + node-express app today and try to implement saml with IDP-initiated SLO.
My version :  "passport": "^0.6.0",   "passport-saml": "^3.2.1".

I struggle with same problems, found the same boggus examples.

Finally I came to a "solution"...
Like @srd90 said, we need to use passpost.authenticate.

```
router.get('/logout/cb',
  passport.authenticate(
    'saml',
    {
      failureRedirect: '/logout/fail', failureMessage: false,
    },
  ),
);

```

Problem is in strategy.js file (found in passport-saml/lib/passport-saml).
In the validateCallback function definition, there is :
`req.logout();`

This call fails : it needs a callback...

So, I try to path this with :

```
// provide a fake one or a real one passed in options.fnCb
const cb = (options.fnCb?.bind(null, req) || (() => {}));
req.logout(cb);

```
All my tests are only done with IDP-initiated SLO and works... 
I use Redis, and session is destroyed everytime.
See function processValidlySignedSamlLogoutAsync in passport-saml/lib/node-saml/saml.js

```
if (response) {
    return { profile: null, loggedOut: true };
}

```

The middleware can use a callback if needed and received the req as parameter:

```
router.get('/logout/cb',
  passport.authenticate(
    'saml',
    {
      fnCb: (req) => {
        if(req?.session?.passport && req.session.passport.user) {
          req.session.destroy();
        }
      },
      failureRedirect: '/logout/fail',
      failureMessage: false,
    },
  ),
);


```
'/logout/fail' : is a simple middleware to send my header to Vue app.

Maybe it can help... 
or maybe my "patch" introduce some other problems... 
but my app don't break the IDP-initiated SLO chain now.

Best

John

**Comment by johndegey** [comment]
Hello @srd90,

I think that it works in my case, because we are in "the best situation".
All apps are in the corporate network, share the same domain name and coookies are mandatory, you can't pass the idp without them.

I did not find any other solution than patching this file for having the SLO chain working like expected, again, in my situation.

Best,
John

**Comment by cjbarth** [comment]
Is this still an open issue @arneroen ? If so, please reply to this thread and we'll reopen the issue.
