### ISSUE TITLE
npm @types/passport-saml is wrong

### ISSUE THREAD

**Issue by matthewaveryusa** [node-saml/passport-saml#348]
Is there any interest in making the typescript dependency (@types/passport-saml) a bit better? I've ran in to a couple issues where the typescript is plain broken:

The MultiSamlStrategy is incorrectly declaring a class while javascript exports the class as a global, 
The callbacks should return Profile types, not objects

I'm more than willing to contribute back the fixes I made, but it's unclear how this project is linked/has influence on the typescript headers declared in @types/passport-saml ?

**Comment by matthewaveryusa** [comment]
another one: 
entryPoint and issuer are declared as required config fields, and the MultiSamlConfig inherits from it, meaning you need to define a bogus entryPoint and issuer.

**Comment by markstos** [comment]
@matthewaveryusa That project is unrelated to this one. Improving TypeScript support is welcome, but I don't know how to best start with that.

**Comment by cjbarth** [comment]
@matthewaveryusa I try to keep the types for `passport-saml` over at https://github.com/DefinitelyTyped/DefinitelyTyped up to date. It is from there that the `@types` packages get published. If there is an update needed, please follow their process for making the update. Don't hesitate to add your name to the maintainer of the types if you'd like. I'll end up getting pinged when you make your PR because I'm listed as a maintainer.

**Comment by cjbarth** [comment]
The latest versions of `passport-saml` and `node-saml` are written in TypeScript, so external types are no longer required.
