### ISSUE TITLE
Getting `issuer` in `getSamlOptions(request)` of `MultiSamlStrategy`

### ISSUE THREAD

**Issue by catamphetamine** [node-saml/passport-saml#439]
Currently, there's `MultiSamlStrategy` with `getSamlOptions(request)`.
The `request` is a generic Node.js HTTP `IncomingMessage`.
But why is it the only argument of `getSamlOptions()`?
Isn't the point of `MultiSamlStrategy` existing to choose SAML config based on which SAML server requests authentication?
If yes, then why isn't `issuer` available in `getSamlOptions()`?.
Currently, we had to work around that via:

```js
import xml2js from 'xml2js';
async function getIssuerFromSamlAuthenticationRequest(request) {
  const samlResponse = new Buffer(querystring.parse(request.body).SAMLResponse, 'base64');
  const samlResponseXml = await xml2js.parseStringPromise(samlResponse.toString());
  return samlResponseXml['saml2p:Response']['saml2:Issuer'][0]['_'];
}
```

----

Also, other people @ssbrewster have pointed that out:

https://github.com/bergie/passport-saml/issues/373#issuecomment-497692011

> Decoupling the decryption from `validatePostResponse` would be great as part of this for e.g. extracting the `Issuer` from an encrypted message in a `MultiSamlStrategy`'s `getSamlOptions` method (arguably it could be done before a v2.0).

**Comment by stavros-wb** [comment]
> If yes, then why isn't issuer available in getSamlOptions()?.

The method is called before SAML instantiation, so all the parsing/decrypting and (get kind of request) are not yet available. It's up to the user to select the appropriate configuration based on the request object. Which could be what you've implemented (perfectly fine) or something even simpler like, the actual URL. What we do is have different endpoints per IDP so we can fetch the configurations based on URL params instead of parsing the SAML messages.

**Comment by catamphetamine** [comment]
Ok, so the reason `Issuer` is not available is because it's not verified.
I don't think that could be a valid reason but whatever, I have my ways of obtaining it, and that works.

**Comment by crossan007** [comment]
I'm in the same situation here;  I have an unverified SAMLResponse which I want to verify; however, I have multiple potential SAML IdP configurations which could be used to verify the response.

Only one of the providers will actually verify the SAMLResponse (since the cert is unique), but I want to know _which_ provider configuration I should return from `getSamlOptions` given the current response.

I was hoping Passport could provide the `saml2:Issuer` out of the response body _before_ validating the signature within `MultiSamlStrategy` to make it easier to identify which configuration should be used to validate the response.

**Comment by crossan007** [comment]
For anyone looking to solve this problem in a different way: look at using `RelayState`.

In `getSamlOptions` , you have access to the request body from the IdP's SAMLResponse.

If you set a `RelayState` on the SAMLRequest containing the name of the provider configuration you want Passport to use, you can simply consume that value within `getSamlOptions`

**Comment by cjbarth** [comment]
@crossan007 that is a valid, spec-compliant way of using RelayState. RelayState is supposed to round-trip from the IdP untouched for just such a purpose. Or, redirecting after login, or whatever, it is your payload.

**Comment by tomer-amir** [comment]
Just to add a bit, as I am having the same issue.
RelayState on works if you are doing an SP Initiated flow... if the user does an IDP Initiated flow, this will still fail.

I'd be happy if we could still add support for this, but for now I am also parsing the SAMLResponse by myself

**Comment by cjbarth** [comment]
Add support for what @tomer-amir ? We shouldn't be returning any information from an unverified SAML payload, so I'm not sure what other idea you had in mind for achieving what you're after. Feel free to post a suggestion here and we can see what might work.

**Comment by tomer-amir** [comment]
> Add support for what @tomer-amir ? We shouldn't be returning any information from an unverified SAML payload, so I'm not sure what other idea you had in mind for achieving what you're after. Feel free to post a suggestion here and we can see what might work.

@cjbarth The library can either supply the unverified data or export the parsing method so we can extract the information ourselves. this way we would not need to parse the XML ourselves to fetch the data :)
as I think the IDP initiated flow is very common, I think this will be a common use case for service providers who support multiple IDPs.

WDYT? :)

**Comment by crossan007** [comment]
I don't have the whole flow fresh in my mind here, but I wonder if this would be a good opportunity to accept an optional callback method in the parameter sets that allows the developer to pre-process the unverified claim.

This approach could provide contextual hints about the trustworthiness of the claim, and possibly allow for additional library-enforced safeguards.

**Comment by cjbarth** [comment]
@crossan007 , please flesh out your ideas and post them here. I've reopened the issue.
