### ISSUE TITLE
Option to have multiple keys in decryptionPvk

### ISSUE THREAD

**Issue by asaheba93** [node-saml/passport-saml#444]
Currently, there is a client and server setup, where the server will be transitioning from an expiring certificate to a new certificate.

I have received the XML metadata of the server and configured passport-saml on the client for which this metadata is stored in the certs option as an array. 
Ex: 
certs: [
'cert1', 
'cert2']

The client (SP) cannot decrypt the encrypted asssertion from the IDP and is erroring out upon receiving a response. The SP is currently using the new certificate for the server. 

I believe the issue is that the IDP is providing an encrypted assertion based off of the old certificate rather than the new certificate, since the server has two certificates (old and new) associated with it.

Is there a way to have multiple private keys for the  decrpytionPvK field, so that I can decrypt the response? This way if I store both keys in an array, it will not matter if the IDP is sending an encrypted assertion based off the old or new certificate, since the SP will be able to successfuly decrypt it. 

Proposed solution: decryptionPvk to accept an array of strings instead of just a single string.

**Comment by ssypi** [comment]
I don't know what the spec says, but it is quite normal in federated identity systems to have two certificates during rollover period when changing the certificates. Also other service provider softwares such as Shibboleth service provider support this as well.

**Comment by luflow** [comment]
@ssypi and @asaheba93 did you have any insights on this? We are also facing the issue now in a federated system (DFN AAI) that we cannot rotate the certs without having the old and the new decryption key at hand at the same time to make sure the IdPs have time to catch up with the new metadata.

It looks like we have to extend the idea of node-saml/node-saml#23 to the decryptionPvk setting and try to decrypt with all private keys that are provided in the settings.

We may contribute to this if it would be the correct way, does anyone of you think thats not the right way?

**Comment by luflow** [comment]
I actually also don't get the sentence in the readme:
https://github.com/node-saml/node-saml/blob/master/README.md?plain=1#L163

`The decryptionCert argument should be a public certificate matching the decryptionPvk and is required if the strategy is configured with a decryptionPvk.`

That would still mean in a federated setup, that all of the IdPs would have to catch up with the new certificate at the same time AND I have to know when they actually catch up so that I can replace the decryptionPvk just in time to have no downtime. So it would actually be better to also be able to have two decryptionPvk in the setup for 24h so that new and old enrcypted assertions can be decrypted.

Would be somehow something like "first try old, then try new private key for decryption"

Or am I misunderstanding something in the SAML flow?

**Comment by luflow** [comment]
So actually we found a different solution thats actually quite simple: We just create new certificates with the old private key - the private key can then decrypt both payloads of the IdPs - doesn't matter if they were encrypted with the old or the new cert ;) As easy as that.
