### ISSUE TITLE
Possibility to choose the account if the user is logged in with the single account

### ISSUE THREAD

**Issue by pslotinsky** [node-saml/passport-saml#501]
When user signed with his personal account **only**, authentication failed with error:  "403 app_not_configured_for_user"

I found this workaround on stackoverflow: https://stackoverflow.com/questions/48806629/google-saml-app-not-configured-for-user-equivalent-of-prompt-select-account-sa

It would be great if you could consider it as a new feature

**Comment by markstos** [comment]
Unless I misunderstand, this would be something that would be implemented outside of `passport-saml`. Our project contains no Google-specific code and we don't intend to add exceptions for various "account choosers".

If there's a specific patch to consider, go ahead and open a pull request, or add something to the the wiki if there's a suggested solution to this, but since I don't see how this would be implemented in passport-saml, I'm closing this issue.
