### ISSUE TITLE
[BUG] Invalid SAML response gets validated

### ISSUE THREAD

**Issue by HendrikJan** [node-saml/passport-saml#547]
I am not sure, but I seem to have found a bug in the validation.

See #546

I edited a valid response (changed "https://evil-corp.com" to "https://hacker-corp.com" in two places) and the validation does not result in "Invalid response".

**To Reproduce**

Run the tests in #546

**Expected behavior**

Because the response is messed with, the validation should result in "Invalid response" but it does result in "SAML assertion expired".

**Environment**

- Node.js version: v15.8.0
- passport-saml version: 2.0.5

The problem seems to originate here:

https://github.com/node-saml/passport-saml/blob/8a1a377f568fa017643404ba67127cd6928e1581/src/passport-saml/saml.ts#L783-L786

The method `this.validateSignature()` returns a `false` when the signature is missing but also when the signature is wrong.
I think that in the case of an invalid signature, at this point in the code an error "Invalid signature" should be thrown.

**Comment by srd90** [comment]
comments after looking at #546

---

First of all lets inspect how test case which uses  `valid/response.root-signed.assertion-signed.xml` behaves because it is quite odd that your test receives "Assertion expired" (one could have expected for example issuer mismatch if/when issuer element at samlp namespace mismatch with issuer element at saml namespace).
So  when `R1A - both signed => valid` test case is executed (link points to version at passport-saml's master branch):
https://github.com/node-saml/passport-saml/blob/8a1a377f568fa017643404ba67127cd6928e1581/test/test-signatures.spec.ts#L50-L53
I would not expect to see assertion expired because I would expect that test case controls current time behind the scenes so that response is processed without any exceptions.

Lets put break point to both of these lines and see what happens when aforementioned test case is executed:
https://github.com/node-saml/passport-saml/blob/8a1a377f568fa017643404ba67127cd6928e1581/src/passport-saml/saml.ts#L1262-L1263
First time when we hit break points value of `notOnOrAfter` is `2020-09-25T16=7:00:00+00:00` (note `=` character) because of this
https://github.com/node-saml/passport-saml/blob/8a1a377f568fa017643404ba67127cd6928e1581/test/static/signatures/valid/response.root-signed.assertion-signed.xml#L13
and `notOnOrAfterMs` becomes `NaN` and test is `some value >= NaN` ... why author of `response.root-signed.assertion-signed.xml` and this testase wanted to have such value...dunno. Should there be failure due this issue ... don't have time to investigate...

Second  time break points are hit when this
https://github.com/node-saml/passport-saml/blob/8a1a377f568fa017643404ba67127cd6928e1581/test/static/signatures/valid/response.root-signed.assertion-signed.xml#L16
is processed. This time code ends up executing this:
https://github.com/node-saml/passport-saml/blob/8a1a377f568fa017643404ba67127cd6928e1581/src/passport-saml/saml.ts#L1263

So `R1A - both signed => valid` is having same "Assertion expired" issue under the hood. Why is test case passing? Dunno. Maybe someone who really knows what happens at these lines can explain why this test case is reporting success:
https://github.com/node-saml/passport-saml/blob/8a1a377f568fa017643404ba67127cd6928e1581/test/test-signatures.spec.ts#L32-L36
because message processing is definitely throwing exception while at the same time it is invoking signature check only once. Its as if passing `validateSignatureSpy.callCount.should.eql(amountOfSignatureChecks);` would be considered sufficient even if message processing ended up having exception.

Eitherway reference testcase seems to have issues/problems of its own. From your pull request's/question's point of view "Assertion expired" is not a "surprise".

---

Now lets move to case you have in this pull request.

passport-saml considers missing or invalid top level signature as "soft error" (assuming that `cert` option with IdP certificate was provided).
https://github.com/node-saml/passport-saml/blob/8a1a377f568fa017643404ba67127cd6928e1581/src/passport-saml/saml.ts#L783-L786
i.e. it leaves value of `validSignature` to `false` and proceeds to check whether assertion's signature is valid:
https://github.com/node-saml/passport-saml/blob/8a1a377f568fa017643404ba67127cd6928e1581/src/passport-saml/saml.ts#L804-L811
and because you modified only content of surrounding `samlp` stuff instead of assertion's stuff signature of assertion's content is valid and passport-saml proceeds to consume it. See also https://github.com/node-saml/passport-saml/pull/536#issuecomment-778838859

Quote from https://wiki.shibboleth.net/confluence/pages/viewpage.action?pageId=55804373
>As long as one of the response or assertion are signed, use of the profile is "safe" in terms of authentication integrity, but there are vulnerabilities in XML Encryption that make signing responses advisable when the most common encryption algorithms are used.

It would be a huge security problem if passport-saml would return any values from `samlp` namespace to application because those values MAY be modified by who ever is passing saml login response which - login response - has only/also validly signed assertion to passport-saml (because missing or invalid top level signature is considered "soft error" and if at least assertion signature is valid login is accepted). Quick and definitely **not too careful code browsing** gives an impression that values returned to application are taken from assertion and none of the values from `samlp` namespace are returned to application.

You would have to introduce another flag to passport saml so that it would consider missing or invalid top level signature as "hard error". Of course you would have to make sure that your IdP is signing samlp (response). For example Shibboleth IdP signs response by default and assertion signing is optional (if e.g. SP gives "WantAssertionsSigned = true").

Your pull request's testcase 
https://github.com/node-saml/passport-saml/blob/d6557d11bbfe6be05928c1f4b68c9849d447a1d6/test/test-signatures.spec.ts#L76-L83
is failing with the "Assertion expired" under the hoods due same reason as reference case examined at the start of this comment. Why your testcase is failing with such hard error while reference case is not ... dunno ... 

But at the end of the date and based on how passport-saml is currently implemented testcase you defined is actually "success / valid" case i.e. similar to
https://github.com/node-saml/passport-saml/blob/8a1a377f568fa017643404ba67127cd6928e1581/test/test-signatures.spec.ts#L50-L53
with the exception that processed response file has invalid top level signature and amount of signature checks would be 2 (and passport-saml would still throw "SAML assertion expired" but test case would be success due same strange reason as reference case is passing).

**Comment by HendrikJan** [comment]
Thank you for looking into this.
I'll close this issue and the PR as it looks like fixing #523 will fix this issue.

> I would not expect to see assertion expired because I would expect that test case controls current time behind the scenes so that response is processed without any exceptions.

I get the impression from reading the tests that they do not control current time behind the scenes, but instead accept the error "Assertion expired" as signifying a valid response.

I hope #523 is going to be fixed soon.
