### ISSUE TITLE
Audience must be supplied

### ISSUE THREAD

**Issue by bvds** [node-saml/passport-saml#814]
The documentation says that `audience` is optional.  I had to explicitly set it to `false`.

**Environment**

- Node.js version:  v14.19.3
- `passport-saml` version:  4.0.1

**Comment by markstos** [comment]
@cjbarth I'm afraid if I manually edit the Changelog file it will break tooling that automatically updates, but it seems worth mentioning retroactively that this is a breaking change for  `passport-saml` 4.0. The reference I found to link to is this PR:  https://github.com/node-saml/node-saml/pull/25

**Comment by cjbarth** [comment]
The tooling is pretty robust. There is a slight problem with how we did the beta releases for `node-saml` that causes the old changelog to look weird, and there is one line for the CVE that must me manually maintained, but that is super easy to do manually. Otherwise, just adding tags to a PR will adjust how it looks in the changelog. This change is currently listed as a "Major Change" in the [changelog](https://github.com/node-saml/node-saml/blob/40b4620feacd6a3d747be8f38a8927de3b51e894/CHANGELOG.md?plain=1#L193). Do you think it needs to be listed differently?

**Comment by markstos** [comment]
That's perfect! I missed it when combing over the various Major changes in the 4.0 beta releases. Thanks!
