### ISSUE TITLE
Invalid Signature While integrating passport-saml with OAM

### ISSUE THREAD

**Issue by bharatsahulw** [node-saml/passport-saml#835]
Hi All,

Is there any way to integrate the node js with passport-saml by using the OAM metadata file instead of ADFS metadata file? I am using below keys from the metadata file in the passport-saml.

passport.use(/login, new SamlStrategy({
path: "login_file_path",
entryPoint: "Entry url from the metadata file or IDP/SP entry url",
issuer: "my application url",
cert: "x509:certificate from the metadata file",
disableRequestedAuthnContext: true,
authnContext: 'http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows'
}, function(user, done) {
if (user && user.nameID) {
done (null, user)
} else {
done(null, null);
}
}));

Getting Invalid signature error.

**Comment by bharatsahulw** [comment]
Thank you for your reply. 

I am using the below stack:
"passport-saml": "^0.20.0",
Node version: 10

I am using the highlighted in yellow as a cert key from the OAM metadata file.
 
![image](https://user-images.githubusercontent.com/121923105/210789461-f9bf7fb1-730e-4e6c-af5b-97d2629c0a38.png)

**Comment by bharatsahulw** [comment]
Thanks for your concern. I have already in the process of upgradation of the packages and node version.

Though I was facing the issue with the current stack. Will it get resolved after upgrading the package ?

**Comment by cjbarth** [comment]
@srd90 is correct, I won't be spending time looking into problems on deprecated versions, and I doubt anyone else will either. We also won't do a release for any version that old. If there is a serious problem with v3, we _may_ do a release, but otherwise issues and PRs should be against the v4 branch.

Please re-open when you meet that baseline if you still have issues.
